// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApwIpC-1ikyuZlugaG8-KkLqdZAWR034s',
    appId: '1:119212193003:android:2e4bd311fab1439cd2baae',
    messagingSenderId: '119212193003',
    projectId: 'bingo01',
    storageBucket: 'bingo01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb_So5Efo52OTGSEaqARzsN0FLAopt4bI',
    appId: '1:119212193003:ios:ff5e768ca50c8f24d2baae',
    messagingSenderId: '119212193003',
    projectId: 'bingo01',
    storageBucket: 'bingo01.appspot.com',
    androidClientId: '119212193003-a2he1l3l1d55gvdlj84shmadkk96qkad.apps.googleusercontent.com',
    iosClientId: '119212193003-93o1dpki8rrpsu21q2rqsv0h8spp0t9i.apps.googleusercontent.com',
    iosBundleId: 'com.app.bingo',
  );
}
